name: d2ypresence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cloud_firestore: 3.1.18
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.20
  firebase_core: 1.18.0
  firebase_storage: 10.2.18
  flutter_svg: ^1.1.5
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  flutter:
    sdk: flutter
  get: 4.6.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.1.61
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  lottie: ^2.1.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/images/logo.jpeg'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Kredit
      fonts:
        - asset: fonts/kredit-front.ttf
